modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="prefab_goety_altars"
version="${mod_version}"
displayName="Prefab - Goety Ritual Altars"
description='''Two shared Prefab altar items with conditional ritual selection and optional addon content filtering.'''

[[dependencies.prefab_goety_altars]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.prefab_goety_altars]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"

[[dependencies.prefab_goety_altars]]
modId="prefab"
mandatory=true
versionRange="[1.10.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.prefab_goety_altars]]
modId="goety"
mandatory=true
versionRange="[2.5.52.2,)"
ordering="AFTER"
side="BOTH"


[[dependencies.prefab_goety_altars]]
modId="goety_revelation"
mandatory=false
versionRange="[2.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.prefab_goety_altars]]
modId="goetydelight"
mandatory=false
versionRange="[1.4.6,)"
ordering="AFTER"
side="BOTH"
